# These are supported funding model platforms

# github: [USERNAME]
# patreon: USERNAME
# open_collective: offline-chat
# ko_fi: USERNAME
# tidelift: pypi/offline-chat
# custom: ['https://example.com']
